module_specification:
  prompt: Please create a module specification document.
  constraints:
    - "Content should primarily describe design intent and purpose. Avoid specific configuration values as much as possible, and only use them when absolutely necessary. (e.g., good: select low-cost arm64 instances bad: use t4g.nano)"
    - Document based on requirements and development guidelines described in README.md.
    - Do not change key names, types, or order.
    - Use [] to indicate empty lists.
  completion_criteria:
    - Requirement coverage: All resources included in module requirements are documented.
    - Policy compliance: Fully compliant with ../guidelines/infrastructure_design_policy.yaml.
    - Output format adherence: Documented based on the specified template.
  output_format:
    template: |
        /**
         * variables:
         *   - [ key ]: [ value ]
         */

        /**
         * outputs:
         *   - [ key ]: [ value ]
         */

        /**
         * [ resource_1_name ]
         *
         * requirements:
         *   - [ resource_1_requirement_1 ]
         *
         * prohibitions:
         *   - [ resource_1_prohibition_1 ]
         */

        /**
         * [ resource_2_name ]
         *
         * requirements:
         *   - [ resource_2_requirement_1 ]
         *
         * prohibitions: []
         */
      ```

    example_output: |
      ```yaml
      /**
       * variables:
       *   - environment: Environment information
       *   - project: Project name
       */

      /**
       * outputs:
       *   - alb_arn: ALB ARN
       */

      /**
       * ECS Cluster
       *
       * requirements:
       *   - Use environment name and project name
       *
       * prohibitions: []
       */

      /**
       * ECS Service
       *
       * requirements:
       *   - Minimum 2 instances for production environment, minimum 1 instance for other environments, with CPU load-based scaling
       *   - Use serverless (Fargate)
       *
       * prohibitions:
       *   - Must not be placed in Public Subnet
       */

      /**
       * ECS Task Definition
       *
       * requirements:
       *   - Use lightweight tasks
       *   - Adopt awsvpc mode
       *
       * prohibitions: []
       */

      /**
       * ALB
       *
       * requirements:
       *   - Use environment name and project name
       *
       * prohibitions: []
       */
      ```
